---
- name: Install podman
  ansible.builtin.apt:
    name: podman
    state: present

- name: Install podman-compose
  ansible.builtin.apt:
    name: podman-compose
    state: present
  when: podman_install_compose | bool
